dataset:
  name: chase
  num_classes: 2
  ignore_index: 255
  img_size: [512, 512]
  crop_size: [512, 512]
  hf_id: "Zomba/CHASE_DB1-retinal-dataset"
  hf_image_key: image
  hf_mask_key: label
  hf_splits:
    train: train
    val: validation
    test: test
